name: 'DBT_TRAINING_DEMO'
profile: 'SNOWFLAKE_DEMO_DB'


model-paths: ["models"]
models:
  DBT_TRAINING_DEMO:
    raws:
      +materialized: view
      +schema: RAW
    transforms:
      +materialized: table
      +schema: TRANSFORM
    consumptions:
      +materialized: view
      +schema: CONSUMPTION


