create table <DATABASE>.<SCHEMA>.AUDIT_LOG( INVOCATION_ID VARCHAR(255), MODEL_NAME VARCHAR(255),
    STATUS VARCHAR(255), START_TIME TIMESTAMP, END_TIME TIMESTAMP,USER_NAME VARCHAR(255));
	
	
    +pre-hook:
      - "INSERT INTO DBT_DEMO.AUDIT.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME,USER_NAME) VALUES ('{{ invocation_id }}','{{ this.name }}','STARTED',CURRENT_TIMESTAMP,NULL,'{{ target.user }}')"
    +post-hook:
      - "INSERT INTO DBT_DEMO.AUDIT.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME,USER_NAME) VALUES ('{{ invocation_id }}','{{ this.name }}','COMPLETED',NULL,CURRENT_TIMESTAMP,'{{ target.user }}')"
on-run-start:
  - "INSERT INTO DBT_DEMO.AUDIT.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME,USER_NAME) VALUES ('{{ invocation_id }}','ON-RUN-START','STARTED',CURRENT_TIMESTAMP,NULL,'{{ target.user }}')"
on-run-end:
  - "INSERT INTO DBT_DEMO.AUDIT.AUDIT_LOG (INVOCATION_ID,MODEL_NAME,STATUS,START_TIME,END_TIME,USER_NAME) VALUES ('{{ invocation_id }}','ON-RUN-END','COMPLETED',NULL,CURRENT_TIMESTAMP,'{{ target.user }}')"	
